# Generated by Django 5.0.4 on 2024-05-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=50, unique=True, verbose_name='question')),
                ('option1', models.CharField(max_length=50, verbose_name='option1')),
                ('option2', models.CharField(max_length=50, verbose_name='option2')),
                ('option3', models.CharField(max_length=50, verbose_name='option3')),
                ('option4', models.CharField(max_length=50, verbose_name='option4')),
                ('answer', models.CharField(choices=[('option1', 'option1'), ('option2', 'option2'), ('option3', 'option3'), ('option4', 'option4')], help_text='choose the correct answer', max_length=7, verbose_name='answer')),
                ('status', models.BooleanField(default=False, verbose_name='status')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
            },
        ),
        migrations.CreateModel(
            name='UserResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=20)),
                ('totall', models.PositiveSmallIntegerField(default=0, verbose_name='all questions')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='result')),
                ('percent', models.FloatField(max_length=5, verbose_name='percentage')),
                ('correct', models.PositiveSmallIntegerField(default=0)),
                ('wrong', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'resuilt',
                'verbose_name_plural': 'resuilts',
            },
        ),
    ]
